metal:
  children:
    masters:
      hosts:
        metal0: { ansible_host: k3s-master-01.lab.ewood.dev }
        metal1: { ansible_host: k3s-master-02.lab.ewood.dev }
        metal2: { ansible_host: k3s-master-03.lab.ewood.dev }
    workers:
      hosts:
        metal3: { ansible_host: k3s-worker-01.lab.ewood.dev }
        metal4: { ansible_host: k3s-worker-02.lab.ewood.dev }
        metal5: { ansible_host: k3s-worker-03.lab.ewood.dev }
