cloudflared:
  credentials:
    existingSecret: cloudflared-credentials
  config:
    tunnel: homelab
    ingress:
      - hostname: '*.ewood.dev'
        service: https://ingress-nginx-controller.ingress-nginx
        originRequest:
          noTLSVerify: true
      - service: http_status:404

  podMonitor:
    enabled: true
    metricsEndpoints:
      - port: http
